apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hookline.fullname" . }}-secret
  labels:
    {{- include "hookline.labels" . | nindent 4 -}}
type: Opaque
stringData:
  HL_API_KEY: {{ .Values.auth.apiKey | quote }}
